# Generated by Django 4.0.5 on 2022-06-05 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='bio',
            new_name='bio_description',
        ),
        migrations.RenameField(
            model_name='pet',
            old_name='photo',
            new_name='img_slug',
        ),
    ]
